name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag ghcr.io/unownone/link-shortener:$(date +%s) .

    - uses: macbre/push-to-ghcr@master
      with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  deploy:
    runs-on: ubuntu-latest  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: ${{ secrets.GCL_SERVICE }}
        image: ghcr.io/unownone/link-shortener:latest
        region: asia-east1
      
    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'

